### ISSUE TITLE
"Current metals" isn't saved with game.

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#14]
After selecting my current metals group, if I save and restore my game, no group is selected.

**Comment by legobmw99** [comment]
This is intended

**Comment by MentalMouse** [comment]
Forgive my bluntness, but that... is a bad thing.  You're making an exception to one of the most fundamental features of the game interface, something so basic as to normally go without saying:  A save-and-restore is supposed to preserve all aspects of the game state, exactly as if the game had simply continued.

**Comment by legobmw99** [comment]
I've found in my experience that the game feels more consistent when your metals are unselected when you load in. That's actually the reason for having an unselected state to begin with, rather than simply always having something selected. 

The way I play most often involves days or weeks between loading the same world. I much prefer the consistency of always being able to press the change button once to select iron and steel.

At any rate, the select metals feature in general is as basic as possible. It exists only for the practical reason of I would feel bad requiring the mod to use eight keybinds. It's clunky and doesn't really fit the cannon, and I'm constantly searching for workable alternatives. I don't consider it worth it to make too many changes to it, because I really do want to scrap it entirely

**Comment by MentalMouse** [comment]
Perhaps you should consider a rotary selector like (most recently) PSI.

**Comment by legobmw99** [comment]
I will look into that

**Comment by legobmw99** [comment]
I've redone the way metals are toggled. I am not sure how happy I am with it, but I certainly think it is better than previous ones

![2017-05-20_15 20 01](https://cloud.githubusercontent.com/assets/2401841/26278756/32722d92-3d70-11e7-834f-a8ecabdf2c11.png)


Check out [GUI-Test](https://github.com/legobmw99/Allomancy/tree/GUI-Test) - I will probably push this to master sometime soon

**Comment by MentalMouse** [comment]
It looks promising -- I'm guessing the red sectors are currently burning?  You probably should have some indicator for a metal that's run out, too.  Where can I get a built jar?  (Despite doing My First Repository, I'm not really set up with Git, I've only been doing scripts and config files so far.)

**Comment by legobmw99** [comment]
Empty metals will be greyed out. Here is a[ preview jar](https://www.dropbox.com/s/eypa4qsudtbwg4n/allomancy-2.7.0preview.jar?dl=0)

**Comment by MentalMouse** [comment]
Alas, Dropbox tells me ".jar files can't be previewed".  Just kidding! ;-)  I'll check it out when I get a chance to play.

**Comment by MentalMouse** [comment]
OK, I've used it briefly, it does seem to work.  You might want to tweak the styling a little -- make the icons bigger/more visible, maybe have a border around the circle.

**Comment by legobmw99** [comment]
I think if I wanted to do any better of a job with the icons, they would need to be 32x. I think I will release it as is (doing those eight textures took more time than all the coding for it, by a factor of two) and look at it again in the future

**Comment by MentalMouse** [comment]
OK, it's working OK as is, so polishing can wait.
