### ISSUE TITLE
1.19.2 Config for worldgen?

### ISSUE THREAD

**Issue by RurouniTim** [legobmw99/Allomancy#86]
When generating a world in 1.19.2 (mod version 4.6.1) I'm not seeing a config file to tweak/disable orespawn in either the main config folder or the world's serverconfig. I seem to recall more recent versions having the config in the serverconfig folder of a generated world. Is this bugged or am I overlooking something?

I'm using forge 43.2.4 and removed all other mods to test this.

**Comment by legobmw99** [comment]
Since ore generation now uses the vanilla "Features" registry, it is no longer configurable in the mod's config files. Instead, you can use a vanilla Datapack to edit it, same as if you wanted to disable iron ore from spawning in a world. 

The base files are here: https://github.com/legobmw99/Allomancy/tree/main/src/main/resources/data/allomancy/worldgen

Here's an example of disabling vanilla worldgen with a datapack: https://www.planetminecraft.com/data-pack/minecraft-but-without-ores/

**Comment by RurouniTim** [comment]
ah, that helps clear things up. I appreciate you clarifying and providing some resources. I'll take a look and try figuring it out. Thank you!
